// <auto-generated />
using System;
using AutoRef_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoRef_API.Migrations
{
    [DbContext(typeof(AppDataBase))]
    [Migration("20251218001127_MutuaBase")]
    partial class MutuaBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AutoRef_API.Database.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AutoRef_API.Database.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Anotador")
                        .HasColumnType("longtext");

                    b.Property<int>("MinArbitros")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrimerArbitro")
                        .HasColumnType("longtext");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("SegundoArbitro")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AutoRef_API.Database.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("AutoRef_API.Database.Competicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsFederada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Competiciones");
                });

            modelBuilder.Entity("AutoRef_API.Database.Disponibilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Franja1")
                        .HasColumnType("int");

                    b.Property<int>("Franja2")
                        .HasColumnType("int");

                    b.Property<int>("Franja3")
                        .HasColumnType("int");

                    b.Property<int>("Franja4")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha")
                        .IsUnique();

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaEnvioMutua")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GeneradoPorUsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GeneradoPorUsuarioId");

                    b.ToTable("EnviosMutua");
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutuaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EnvioMutuaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("InscripcionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EnvioMutuaId");

                    b.HasIndex("InscripcionId");

                    b.ToTable("EnviosMutuaItems");
                });

            modelBuilder.Entity("AutoRef_API.Database.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ClubId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("AutoRef_API.Database.Inscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CompeticionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MutuaSolicitada")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("PersonaId", "EquipoId", "CompeticionId")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("AutoRef_API.Database.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Leida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("AutoRef_API.Database.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AnotadorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Arbitro1Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Arbitro2Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EquipoLocalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EquipoVisitanteId")
                        .HasColumnType("char(36)");

                    b.Property<int>("EstadoAnotador")
                        .HasColumnType("int");

                    b.Property<int>("EstadoArbitro1")
                        .HasColumnType("int");

                    b.Property<int>("EstadoArbitro2")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<Guid?>("LugarId")
                        .HasColumnType("char(36)");

                    b.Property<int>("NumeroPartido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnotadorId");

                    b.HasIndex("Arbitro1Id");

                    b.HasIndex("Arbitro2Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("LugarId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("AutoRef_API.Database.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaEnvioMutua")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MutuaEnviada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid?>("UltimoEnvioMutuaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("UltimoEnvioMutuaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("AutoRef_API.Database.Polideportivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("Latitud")
                        .HasColumnType("double");

                    b.Property<double>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Polideportivos");
                });

            modelBuilder.Entity("AutoRef_API.Database.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ClubVinculadoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<double>("Latitud")
                        .HasColumnType("double");

                    b.Property<int>("Licencia")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("Nivel")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClubVinculadoId");

                    b.HasIndex("Licencia")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoRef_API.Database.Disponibilidad", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutua", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", "GeneradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("GeneradoPorUsuarioId");

                    b.Navigation("GeneradoPorUsuario");
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutuaItem", b =>
                {
                    b.HasOne("AutoRef_API.Database.EnvioMutua", "EnvioMutua")
                        .WithMany("Items")
                        .HasForeignKey("EnvioMutuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvioMutua");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("AutoRef_API.Database.Equipo", b =>
                {
                    b.HasOne("AutoRef_API.Database.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoRef_API.Database.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Categoria");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("AutoRef_API.Database.Inscripcion", b =>
                {
                    b.HasOne("AutoRef_API.Database.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");

                    b.Navigation("Equipo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AutoRef_API.Database.Notificacion", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoRef_API.Database.Partido", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", "Anotador")
                        .WithMany()
                        .HasForeignKey("AnotadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Usuario", "Arbitro1")
                        .WithMany()
                        .HasForeignKey("Arbitro1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Usuario", "Arbitro2")
                        .WithMany()
                        .HasForeignKey("Arbitro2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("AutoRef_API.Database.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Polideportivo", "Lugar")
                        .WithMany()
                        .HasForeignKey("LugarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Anotador");

                    b.Navigation("Arbitro1");

                    b.Navigation("Arbitro2");

                    b.Navigation("Categoria");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("AutoRef_API.Database.Persona", b =>
                {
                    b.HasOne("AutoRef_API.Database.EnvioMutua", "UltimoEnvioMutua")
                        .WithMany()
                        .HasForeignKey("UltimoEnvioMutuaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UltimoEnvioMutua");
                });

            modelBuilder.Entity("AutoRef_API.Database.Usuario", b =>
                {
                    b.HasOne("AutoRef_API.Database.Club", "ClubVinculado")
                        .WithMany()
                        .HasForeignKey("ClubVinculadoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ClubVinculado");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutua", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
