// <auto-generated />
using System;
using AutoRef_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoRef_API.Migrations
{
    [DbContext(typeof(AppDataBase))]
    partial class AppDataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AutoRef_API.Database.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AutoRef_API.Database.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Anotador")
                        .HasColumnType("longtext");

                    b.Property<int>("MinArbitros")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PrimerArbitro")
                        .HasColumnType("longtext");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("SegundoArbitro")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AutoRef_API.Database.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FederacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValue(new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FederacionId", "Nombre")
                        .IsUnique();

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("AutoRef_API.Database.Competicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsFederada")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("FederacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValue(new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FederacionId", "Nombre")
                        .IsUnique();

                    b.ToTable("Competiciones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("012f80f7-3b7d-4df2-8a07-35e80c0ba0b0"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CAMPEONATO DE ASTURIAS BENJAMIN FEMENINO"
                        },
                        new
                        {
                            Id = new Guid("b5e0c3c9-0d3b-4a4d-8d66-0ad8f91b2f6e"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "JUEGOS DEPORTIVOS BENJAMIN MIXTO"
                        },
                        new
                        {
                            Id = new Guid("624f3f92-cf13-4fa7-bc4b-53c9fd2e6b6b"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CAMPEONATO DE ASTURIAS ALEVIN MASCULINO"
                        },
                        new
                        {
                            Id = new Guid("9714711c-b47a-4aa7-b923-7b9c0b90d385"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CAMPEONATO DE ASTURIAS ALEVIN FEMENINO"
                        },
                        new
                        {
                            Id = new Guid("5c6e5ea5-7af8-437f-a9f2-1f6b16c08a2c"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "JUEGOS DEPORTIVOS ALEVIN MIXTO"
                        },
                        new
                        {
                            Id = new Guid("6e53d4b1-f35c-4d68-b8a0-468b06605c64"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "JUEGOS DEPORTIVOS INFANTIL MASCULINO"
                        },
                        new
                        {
                            Id = new Guid("4ce48b7a-7c1a-4a84-8b30-e150d37ca006"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "JUEGOS DEPORTIVOS 1ª DIVISIÓN INFANTIL FEMENINO"
                        },
                        new
                        {
                            Id = new Guid("a1c760f2-a6f8-451b-8614-8ed95d40182b"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "JUEGOS DEPORTIVOS 2ª DIVISIÓN INFANTIL MIXTO"
                        },
                        new
                        {
                            Id = new Guid("d2bf94da-08a1-4fdc-8d7b-945e52a23b58"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "JUEGOS DEPORTIVOS CADETE MASCULINO"
                        },
                        new
                        {
                            Id = new Guid("80a146e0-7c3f-4e5c-8ca3-2d9bb56a1d0c"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "JUEGOS DEPORTIVOS 1ª DIVISIÓN CADETE FEMENINO"
                        },
                        new
                        {
                            Id = new Guid("376842d8-2f21-4f79-a0e2-e4b809c8a02a"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "JUEGOS DEPORTIVOS 2ª DIVISIÓN CADETE FEMENINO"
                        },
                        new
                        {
                            Id = new Guid("2a2602f8-5f1a-4e02-8ef6-4a1ce41c4b4f"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CAMPEONATO DE ASTURIAS JUVENIL MASCULINO"
                        },
                        new
                        {
                            Id = new Guid("c3e8c8e2-3cfe-4b1c-8a7f-9b6b567a7f9a"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CAMPEONATO DE ASTURIAS JUVENIL FEMENINO"
                        },
                        new
                        {
                            Id = new Guid("c0db6dd5-5709-41e0-b8d3-f70222b2c1e4"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CAMPEONATO DE ASTURIAS SEGUNDA DIV. MASCULINA"
                        },
                        new
                        {
                            Id = new Guid("6b47f3a0-0c87-4cf2-8b4e-90c2a0a4db8d"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "PRIMERA DIVISION SENIOR MASCULINA"
                        },
                        new
                        {
                            Id = new Guid("75fa3c5a-3335-468e-94a2-8d7c4f6c57a6"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "SUPERLIGA 2 SENIOR MASCULINA"
                        },
                        new
                        {
                            Id = new Guid("a73b0e31-2f05-4b64-9a8e-448e2a1e8b5f"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CAMPEONATO DE ASTURIAS SEGUNDA DIV. FEMENINA"
                        },
                        new
                        {
                            Id = new Guid("d3a11a4b-b9c2-4d07-9b4e-67b7f532a6d1"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "PRIMERA DIVISIÓN SENIOR FEMENINA"
                        },
                        new
                        {
                            Id = new Guid("8b4bf1f1-215a-4c27-a7b6-1c6c3a1b6d5d"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "SUPERLIGA 2 SENIOR FEMENINA"
                        },
                        new
                        {
                            Id = new Guid("f8a5e909-4a6a-4a1d-84d9-64283a4ab4e4"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "JUEGOS DEPORTIVOS MINIBENJAMIN MIXTO"
                        },
                        new
                        {
                            Id = new Guid("1d0c0e1d-4e64-44f5-9f08-3fe6a6f4e0d9"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CIRCUITO REGIONAL VOLEY PLAYA SENIOR FEMENINO"
                        },
                        new
                        {
                            Id = new Guid("c2d56f5b-62ab-4b7f-9b3b-04f06c9f8a87"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CAMPEONATO DE ASTURIAS JUNIOR MASCULINO"
                        },
                        new
                        {
                            Id = new Guid("e5f7f38a-6261-4e9d-a0d5-5d90f2e4e5a1"),
                            Activa = true,
                            EsFederada = true,
                            FederacionId = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "CAMPEONATO DE ASTURIAS JUNIOR FEMENINO"
                        });
                });

            modelBuilder.Entity("AutoRef_API.Database.Disponibilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Franja1")
                        .HasColumnType("int");

                    b.Property<int>("Franja2")
                        .HasColumnType("int");

                    b.Property<int>("Franja3")
                        .HasColumnType("int");

                    b.Property<int>("Franja4")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha")
                        .IsUnique();

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaEnvioMutua")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GeneradoPorUsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GeneradoPorUsuarioId");

                    b.ToTable("EnviosMutua");
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutuaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EnvioMutuaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("InscripcionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EnvioMutuaId");

                    b.HasIndex("InscripcionId");

                    b.ToTable("EnviosMutuaItems");
                });

            modelBuilder.Entity("AutoRef_API.Database.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ClubId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("AutoRef_API.Database.Federacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Federaciones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f5a71bb-7f19-4f2d-8f8c-580eec7a9375"),
                            Nombre = "Federación Asturiana"
                        });
                });

            modelBuilder.Entity("AutoRef_API.Database.Inscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CompeticionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MutuaSolicitada")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("PersonaId", "EquipoId", "CompeticionId")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("AutoRef_API.Database.LicenciaCategoriaHabilitada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LicenciaPersonaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("LicenciaPersonaId", "CategoriaId")
                        .IsUnique();

                    b.ToTable("LicenciasCategoriasHabilitadas");
                });

            modelBuilder.Entity("AutoRef_API.Database.LicenciaPersona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("CategoriaBaseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClubSolicitanteId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaSolicitudUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaValidacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ModalidadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroLicencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ValidadaPorUsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaBaseId");

                    b.HasIndex("ModalidadId");

                    b.HasIndex("TemporadaId");

                    b.HasIndex("PersonaId", "TemporadaId", "ModalidadId")
                        .IsUnique();

                    b.ToTable("LicenciasPersonas");
                });

            modelBuilder.Entity("AutoRef_API.Database.Modalidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Modalidades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a6a2a2f-6136-4c38-9b25-3a6a2a7e4e1b"),
                            Activa = true,
                            Nombre = "Voleibol"
                        });
                });

            modelBuilder.Entity("AutoRef_API.Database.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Leida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("AutoRef_API.Database.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AnotadorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Arbitro1Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Arbitro2Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CompeticionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EquipoLocalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EquipoVisitanteId")
                        .HasColumnType("char(36)");

                    b.Property<int>("EstadoAnotador")
                        .HasColumnType("int");

                    b.Property<int>("EstadoArbitro1")
                        .HasColumnType("int");

                    b.Property<int>("EstadoArbitro2")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRespuestaAnotadorUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRespuestaArbitro1Utc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRespuestaArbitro2Utc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierreUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<Guid?>("LugarId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MotivoEstadoAnotador")
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoEstadoArbitro1")
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoEstadoArbitro2")
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroPartido")
                        .HasColumnType("int");

                    b.Property<int?>("ResultadoLocal")
                        .HasColumnType("int");

                    b.Property<int?>("ResultadoVisitante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnotadorId");

                    b.HasIndex("Arbitro1Id");

                    b.HasIndex("Arbitro2Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("LugarId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("AutoRef_API.Database.ActaPartido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadaPorUsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaActualizacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId")
                        .IsUnique();

                    b.ToTable("ActasPartido");
                });

            modelBuilder.Entity("AutoRef_API.Database.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ciudad")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaEnvioMutua")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MutuaEnviada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Provincia")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid?>("UltimoEnvioMutuaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("UltimoEnvioMutuaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("AutoRef_API.Database.Polideportivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("Latitud")
                        .HasColumnType("double");

                    b.Property<double>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Polideportivos");
                });

            modelBuilder.Entity("AutoRef_API.Database.Temporada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Temporadas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a7f4c6-41f2-4d3d-9ab5-5a8e3fd5c2d1"),
                            Activa = true,
                            FechaFin = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Temporada actual"
                        });
                });

            modelBuilder.Entity("AutoRef_API.Database.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ClubVinculadoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<double>("Latitud")
                        .HasColumnType("double");

                    b.Property<int>("Licencia")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("Nivel")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClubVinculadoId");

                    b.HasIndex("Licencia")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoRef_API.Database.Club", b =>
                {
                    b.HasOne("AutoRef_API.Database.Federacion", "Federacion")
                        .WithMany()
                        .HasForeignKey("FederacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Federacion");
                });

            modelBuilder.Entity("AutoRef_API.Database.Competicion", b =>
                {
                    b.HasOne("AutoRef_API.Database.Federacion", "Federacion")
                        .WithMany()
                        .HasForeignKey("FederacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Federacion");
                });

            modelBuilder.Entity("AutoRef_API.Database.Disponibilidad", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutua", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", "GeneradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("GeneradoPorUsuarioId");

                    b.Navigation("GeneradoPorUsuario");
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutuaItem", b =>
                {
                    b.HasOne("AutoRef_API.Database.EnvioMutua", "EnvioMutua")
                        .WithMany("Items")
                        .HasForeignKey("EnvioMutuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvioMutua");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("AutoRef_API.Database.Equipo", b =>
                {
                    b.HasOne("AutoRef_API.Database.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoRef_API.Database.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Categoria");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("AutoRef_API.Database.Inscripcion", b =>
                {
                    b.HasOne("AutoRef_API.Database.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");

                    b.Navigation("Equipo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AutoRef_API.Database.LicenciaCategoriaHabilitada", b =>
                {
                    b.HasOne("AutoRef_API.Database.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.LicenciaPersona", "LicenciaPersona")
                        .WithMany("CategoriasHabilitadas")
                        .HasForeignKey("LicenciaPersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("LicenciaPersona");
                });

            modelBuilder.Entity("AutoRef_API.Database.LicenciaPersona", b =>
                {
                    b.HasOne("AutoRef_API.Database.Categoria", "CategoriaBase")
                        .WithMany()
                        .HasForeignKey("CategoriaBaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoRef_API.Database.Modalidad", "Modalidad")
                        .WithMany()
                        .HasForeignKey("ModalidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaBase");

                    b.Navigation("Modalidad");

                    b.Navigation("Persona");

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("AutoRef_API.Database.Notificacion", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoRef_API.Database.Partido", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", "Anotador")
                        .WithMany()
                        .HasForeignKey("AnotadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Usuario", "Arbitro1")
                        .WithMany()
                        .HasForeignKey("Arbitro1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Usuario", "Arbitro2")
                        .WithMany()
                        .HasForeignKey("Arbitro2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("AutoRef_API.Database.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoRef_API.Database.Polideportivo", "Lugar")
                        .WithMany()
                        .HasForeignKey("LugarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Anotador");

                    b.Navigation("Arbitro1");

                    b.Navigation("Arbitro2");

                    b.Navigation("Categoria");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Lugar");

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("AutoRef_API.Database.ActaPartido", b =>
                {
                    b.HasOne("AutoRef_API.Database.Partido", "Partido")
                        .WithOne("Acta")
                        .HasForeignKey("AutoRef_API.Database.ActaPartido", "PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("AutoRef_API.Database.Persona", b =>
                {
                    b.HasOne("AutoRef_API.Database.EnvioMutua", "UltimoEnvioMutua")
                        .WithMany()
                        .HasForeignKey("UltimoEnvioMutuaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UltimoEnvioMutua");
                });

            modelBuilder.Entity("AutoRef_API.Database.Usuario", b =>
                {
                    b.HasOne("AutoRef_API.Database.Club", "ClubVinculado")
                        .WithMany()
                        .HasForeignKey("ClubVinculadoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ClubVinculado");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRef_API.Database.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AutoRef_API.Database.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoRef_API.Database.EnvioMutua", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AutoRef_API.Database.LicenciaPersona", b =>
                {
                    b.Navigation("CategoriasHabilitadas");
                });
#pragma warning restore 612, 618
        }
    }
}
