name: Build project and deploy to myWindowsHosting.com
on: [push]

jobs:
  build_and_deploy:
    name: Build package and deploy to myWindowsHosting.com
    runs-on: windows-latest
    steps:
      - name: build file
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win8133.site4now.net
          username: voleyasturias-001
          password: Carcaba_51
          server-dir: webautoref/
